remote_theme: jekyll/minima@f1a2af4
plugins:
- jekyll-remote-theme
- jekyll-sitemap
author:
  name: Dylan Walsh
  email: dylanlucas1510@gmail.com
github_username: dyluc
url: "https://dyluc.me"
defaults:
  - scope:
      path: "binhex/**"
    values:
      sitemap: false
title: dyluc.github.io
description: Technical blog on ML, AI systems, and low-level programming.
disqus:
  shortname: dyluc-github-io
minima:
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/dyluc"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/dylan-lucas1510/"
