remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

title: dyluc.me
author: Dylan Walsh
email: dylanlucas1510@gmail.com
url: "https://dyluc.me"
description: Technical blog on ML, AI systems, and low-level programming.

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

# disqus config (need custom integration)
disqus:
  shortname: dyluc-github-io

defaults:
  - scope:
      path: "binhex/**"
    values:
      sitemap: false