remote_theme: jekyll/minima@f1a2af4
plugins:
- jekyll-remote-theme
author:
  name: Dylan Walsh
  email: dylanlucas1510@gmail.com
github_username: dyluc
url: https://dyluc.github.io
title: dyluc.github.io
description: A technical blog on machine learning, AI systems, and low-level programming with practical guides and deep dives.
disqus:
  shortname: dyluc-github-io
minima:
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/dyluc"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/dylan-lucas1510/"