remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
author:
  name: Dylan Walsh
  email: dylanlucas1510@gmail.com
github_username: dyluc
url: https://dyluc.github.io
disqus:
  shortname: dyluc-github-io
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/dyluc" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/dylan-lucas1510/" }
