name: IndexNow Refresh

on:
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Simple GET 
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" --fail-with-body \
            "https://api.indexnow.org/indexnow?url=https://dyluc.me/&key=73f94957-7684-4cbd-98cc-0a97d3522954")

          echo "HTTP status: $response"

          if [ "$response" -ne 200 ] && [ "$response" -ne 202 ]; then
            echo "Failed with status $response"
            exit 1
          fi

          echo "✅"
