name: IndexNow Refresh

on:
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Simple GET 
        run: |
          curl -G https://api.indexnow.org/indexnow?url=https://dyluc.github.io/&key=73f94957-7684-4cbd-98cc-0a97d3522954 \
          && echo "✅"
